services:
  - type: web
    name: anna-university-gpa
    runtime: python
    region: oregon
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr libgl1-mesa-glx
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18